task: triviaqa_adv
dataset_path: EssentialAI/triviaqa_adv
output_type: generate_until
test_split: test
doc_to_text: !function preprocess.doc_to_text
doc_to_target: "{{answer}}"
process_results: !function preprocess.process_results
should_decontaminate: true
doc_to_decontamination_query: question
generation_kwargs:
  #until:
    #- "\n"
    #- "."
    #- ","
  max_gen_toks: 1536
  do_sample: false
  temperature: 0.0
    #filter_list:
    # - name: remove_whitespace
    #filter:
    #  - function: remove_whitespace
    #  - function: take_first
target_delimiter: " "
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
  - metric: answer_exists
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true 
metadata:
  version: 3.0


